services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - app-network

  wavelength:
    image: ${DOCKER_REGISTRY-}wavelengthapi
    build:
      context: .
      dockerfile: Wavelength/Dockerfile
    container_name: wavelength-api
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - ASPNETCORE_URLS=http://+:80
      - Jwt__Audience=github.com/wavelength
      - Jwt__Issuer=github.com/wavelength
      - Jwt__Secret=SuperSecretKeyForJwtTokenGeneration123
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=test_db;Username=test_user;Password=test_password;Pooling=true;
      - Aes__Key=stHHnftN8kDvKFKWDkMUTqos4lrYtav1u+jhwAzFeyo=
    ports:
      - "9080:80"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      seq:
        condition: service_started
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge 