namespace Wavelength.Services
{
    /// <summary>
    /// Defines a contract for retrieving email template content by name.
    /// </summary>
    public interface IEmailTemplateLoader
    {
        /// <summary>
        /// Retrieves the content of a template with the specified name.
        /// </summary>
        /// <param name="name">The name of the template to retrieve. Cannot be null or empty.</param>
        /// <returns>A string containing the template content if found; otherwise, null.</returns>
        string GetTemplate(string name);
    }

    /// <summary>
    /// Provides functionality to load and retrieve embedded HTML email templates by name from the assembly resources.
    /// </summary>
    /// <remarks>This class scans the assembly for embedded HTML templates located in the ".Templates"
    /// resource path and makes them available for retrieval by template name. Template names are case-insensitive.
    /// Typically used to centralize and manage email template content within an application.</remarks>
    public class EmailTemplateLoader : IEmailTemplateLoader
    {
        private readonly Dictionary<string, string> _templates = new();

        /// <summary>
        /// Initializes a new instance of the EmailTemplateLoader class and loads embedded HTML email templates from the
        /// assembly's resources.
        /// </summary>
        /// <remarks>This constructor scans the assembly for embedded resources located in the
        /// ".Templates." namespace and ending with the ".html" extension. Each template is loaded and made available
        /// for later retrieval by key. The keys are generated by removing the namespace and file extension, and
        /// converting the result to lowercase. This enables case-insensitive access to templates by name.</remarks>
        public EmailTemplateLoader()
        {
            var assembly = typeof(EmailTemplateLoader).Assembly;
            var resourceNames = assembly.GetManifestResourceNames();

            foreach (var resource in resourceNames)
            {
                if (resource.Contains(".Templates.") && resource.EndsWith(".html"))
                {
                    using var stream = assembly.GetManifestResourceStream(resource);
                    if (stream != null)
                    {
                        using var reader = new StreamReader(stream);

                        var content = reader.ReadToEnd();

                        var key = resource
                            .Replace("Wavelength.Templates.", "")
                            .Replace(".html", "")
                            .ToLower();

                        _templates[key] = content;
                    }
                }
            }
        }

        /// <summary>
        /// Retrieves the HTML template content associated with the specified template name.
        /// </summary>
        /// <param name="name">The name of the template to retrieve. The comparison is case-insensitive.</param>
        /// <returns>A string containing the HTML content of the specified template.</returns>
        /// <exception cref="FileNotFoundException">Thrown if a template with the specified name does not exist.</exception>
        public string GetTemplate(string name)
        {
            if (_templates.TryGetValue(name.ToLower(), out var html))
                return html;

            throw new FileNotFoundException($"Template '{name}' blev ikke fundet.");
        }
    }
}
