namespace Commons.Enums
{
	public enum Interest
    {
        Politik,
        Videnskab,
        Fitness,
        Oekonomi,
        Ivaerksaetteri,
        Baeredygtighed,
        KoncerterOgFestivaler,
        SerierOgStreaming,
        Kampsport,
        ModeOgStil,
        MeditationOgMindfulness,
        VinOgOel,
        AedruLivsstil,
        HarBoern,
        OenskerBoern,
        OenskerIkkeBoern,
        Backpacking,
        BoegerOgLaesning,
        PersonligUdvikling,
        Introvert,
        Ekstrovert,
        SerioestForhold,
        CasualDating,
        VenskabFoerst,
        Gaming,
        Nature,
        Musik,
        Film,
        Dyr,
        Biler,
        Sport,
        MotorSport,
        Toej,
        Tech,
        Spirituelt,
        Anime,
        Sprog,
        Mad,
        Rejser
    }

    public static class InterestData
    {
        public static readonly IReadOnlyDictionary<Interest, string> Labels =
            new Dictionary<Interest, string>
        {
            { Interest.Politik, "Politik" },
            { Interest.Videnskab, "Videnskab" },
            { Interest.Fitness, "Fitness" },
            { Interest.Oekonomi, "Økonomi" },
            { Interest.Ivaerksaetteri, "Iværksætteri" },
            { Interest.Baeredygtighed, "Bæredygtighed" },
            { Interest.KoncerterOgFestivaler, "Koncerter & Festivaler" },
            { Interest.SerierOgStreaming, "Serier & Streaming" },
            { Interest.Kampsport, "Kampsport" },
            { Interest.ModeOgStil, "Mode & Stil" },
            { Interest.MeditationOgMindfulness, "Meditation & Mindfulness" },
            { Interest.VinOgOel, "Vin & Øl" },
            { Interest.AedruLivsstil, "Ædru livsstil" },
            { Interest.HarBoern, "Har børn" },
            { Interest.OenskerBoern, "Ønsker børn" },
            { Interest.OenskerIkkeBoern, "Ønsker ikke børn" },
            { Interest.Backpacking, "Backpacking" },
            { Interest.BoegerOgLaesning, "Bøger & Læsning" },
            { Interest.PersonligUdvikling, "Personlig udvikling" },
            { Interest.Introvert, "Introvert" },
            { Interest.Ekstrovert, "Ekstrovert" },
            { Interest.SerioestForhold, "Seriøst forhold" },
            { Interest.CasualDating, "Casual dating" },
            { Interest.VenskabFoerst, "Venskab først" },
            { Interest.Gaming, "Gaming" },
            { Interest.Nature, "Nature" },
            { Interest.Musik, "Musik" },
            { Interest.Film, "Film" },
            { Interest.Dyr, "Dyr" },
            { Interest.Biler, "Biler" },
            { Interest.Sport, "Sport" },
            { Interest.MotorSport, "Motor sport" },
            { Interest.Toej, "Tøj" },
            { Interest.Tech, "Tech" },
            { Interest.Spirituelt, "Spirituelt" },
            { Interest.Anime, "Anime" },
            { Interest.Sprog, "Sprog" },
            { Interest.Mad, "Mad" },
            { Interest.Rejser, "Rejser" }
        };
    }
}